server.port: "7778"
spring.h2.console.enabled: "true"

spring.datasource.url: "jdbc:h2:tcp://localhost/~/account"
spring.datasource.username: "s"
spring.datasource.password: 
spring.datasource.driver-class-name: "org.h2.Driver"
spring.jpa.database-platform: "org.hibernate.dialect.H2Dialect"

